export type PaymentType = {
  ID: number;
  price: string;
  dueDate: string;
  sayadiCode: string;
  nationalId: string;
  parentGUID: string;
  dayOfYear: string;
  Title: string;
  status: string;
  agentDescription: string;
  treasuryConfirmDescription: string;
  iban: string;
  name: string;
  serialNo: string;
  seriesNo: string;
  branchCode: string;
  checksColor: string;
  Verified: string;
  VerifiedSayad: string;
  SalesExpert: string;
  SalesExpertAcunt_text: string;
  itemGUID: string;
  sayadConfirmReason: string;
  sayadConfirmHolders: string;
  sayadConfirmBlockStatus: string;
  sayadConfirmChequeStatus: string;
  sayadConfirmChequeType: string;
  sayadConfirmBankCode: string;
  sayadConfirmGuaranteeStatus: string;
};

export type DebtType = {
  parentGUID: string;
  debt: string;
  debtDate: string;
  orderNum: string;
  userName: string;
  dayOfYear: number;
  status: string;
};
